"""Constants module for flaskr app."""

STATUS_NO_CONTENT = 204
STATUS_BAD_REQUEST = 400
STATUS_UNAUTHORIZED = 401
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404
STATUS_METHOD_NOT_ALLOWED = 405
STATUS_UNPROCESSABLE_ENTITY = 422

ERROR_MESSAGES = {
    STATUS_NO_CONTENT: 'No Content',
    STATUS_BAD_REQUEST: 'Bad Request',
    STATUS_UNAUTHORIZED: 'Unauthorized',
    STATUS_FORBIDDEN: 'Forbidden',
    STATUS_NOT_FOUND: 'Not Found',
    STATUS_METHOD_NOT_ALLOWED: 'Method Not Allowed',
    STATUS_UNPROCESSABLE_ENTITY: 'Unprocessable Entity',
}

QUESTIONS_PER_PAGE = 10
