STATUS_BAD_REQUEST = 400
STATUS_UNAUTHORIZED = 401
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404

ERROR_MESSAGES = {
    STATUS_BAD_REQUEST: 'Bad Request',
    STATUS_UNAUTHORIZED: 'Unauthorized',
    STATUS_FORBIDDEN: 'Forbidden',
    STATUS_NOT_FOUND: 'Not Found',
}
